services:
  - type: web
    name: snehulak-smile-dental-clinic
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:mypassword123@db.lwobdoiayyikpzfzpoqq.supabase.co:5432/postgres"
